

spring:
  application:
    name: backend

  jpa:
    open-in-view: false

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

secret-token: ${SECRET_TOKEN}

server:
  port: 8081